# Automatically generated by configure
# Configured with: './configure'
CC = gcc
CXX = g++
AS = as
STRIP = strip
CFLAGS +=  -mfpu=vfp -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -Wno-unused-result
ASFLAGS +=  -mfpu=vfp
LDFLAGS += 
LDLIBS += -L/usr/lib/arm-linux-gnueabihf -lSDL -lasound -ldl -lpng  -lm

ARCH = arm
PLATFORM = generic
SOUND_DRIVERS =  oss alsa sdl
HAVE_LIBAVCODEC = 1
